# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steven's Work in Progress
email: sgbrown@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Steven. This is my site for all things
  dev-related, such as my developer blog, portfolio
  page, and work for the Scrabble community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
include: ['_pages']
github_username:      stevenb-nz
linkedin_username:    stevengraemebrown
linkedin_displayname: Steven Brown

# Google Analytics
google_analytics: UA-112882110-1

# Build settings
markdown: kramdown
