# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steven's Work in Progress
email: sgbrown@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Steven Brown. I've recently retrained as a web developer,
  and this site is where I'll be putting all things dev-related:
  starting with my developer blog, and a projects page.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:      stevenb-nz
linkedin_username:    stevengraemebrown
linkedin_displayname: Steven Brown

# Build settings
markdown: kramdown
